# ==========================================
# CONFIGURACOES DO EXPERIMENTO - GRUPO 6
# ==========================================

# Qual tipo de dado testar? (INT ou STR)
tipoDado=STR

# Quais funcoes testar? (DIVISAO, MULTIPLICACAO, POLINOMIAL, MID-SQUARE e DJB2)
# Pode colocar mais de uma separada por virgula!
# Atencao!! Para o tipo de dados INT só poderá ser escolhidas as seguintes funcoes: 
# DIVISAO, MULTIPLICACAO e MID-SQUARE
tipoHash=POLINOMIAL

# Parametros do JMH (Tamanho do dataset(10000, 100000, 1000000) e fator de carga(0.5, 0.75, 0.9))
n=10000
#,100000,1000000
fatorCarga=0.5,0.75,0.9

# Tamanho das chaves numericas quando tipoDado=INT (7, 8 ou 9 digitos)
# Deixe apenas 7 para o teste mock rodar rapidinho
tamanhoInt=7

# Tamanho das chaves de texto quando tipoDado=STR (10, 50 ou 100 caracteres)
tamanhoStr=10

# Cenario de geracao quando tipoDado=STR (UNIFORME ou PADRAO)
cenarioDados=UNIFORME